version: '2'
services:
  web:
    container_name: web
    build: ./web
    ports:
      - '80:80'
      - '3306:3306'
    tty: true
    restart: always
    volumes:
      - ../recruit:/var/www/recruit:cached
      - ../recruit_db/mysql_data:/var/lib/mysql
